api_platform:
    title: Reason Center API Platform.
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
