auth:
    path: /auth
    methods: [ 'POST' ]
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: ['POST']
